spring:
    application:
        name: djarena-service
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:djarena}?useSSL=false&allowPublicKeyRetrieval=true
        driverClassName: org.postgresql.Driver
        username: ${USERNAME:postgres}
        password: ${PASSWORD:toor}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        baseline-on-migrate: true
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 10MB
            max-request-size: 15MB

object-storage:
    endpoint:
        uri: http://localhost:9000
    credentials:
        access-key: ${OBJECT_STORAGE_ACCESS_KEY:minioadmin}
        secret-key: ${OBJECT_STORAGE_ACCESS_KEY:minioadmin}
    buckets:
        product-preview:
            name: product-preview
            default-image: default.webp

security:
    jwt:
        secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    access-token:
        expiration-time: 3600 # 1h in seconds
    refresh-token:
        expiration-time: 1728000 # 20d in seconds
    role:
        default: USER

logging:
    service-code: djarena-service
    exception-handler-trace: true
